<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Scheduler
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-scheduler
 */
?>
<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php echo $block->getGridHtml() ?>
<input type="hidden" name="schedule[product_ids]" id="assigned_products" data-form-part="edit_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "Magetrend_Scheduler/js/schedule/product/assign": {
                "selectedProducts": <?php /* @escapeNotVerified */ echo $block->getProductsJson() ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>