<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Scheduler
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-scheduler
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magetrend_Scheduler/js/schedule/form": {
                "readonly": <?php echo $block->readOnly()?'true':'false'; ?>
            }
        }
    }
</script>
